---
# Practicalli Spacemacs
site_name: Practicalli Spacemacs
site_url: https://practical.li/spacemacs
site_description: Practical guide to Clojure development with Spacemacs
site_author: Practicalli
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/spacemacs/
edit_uri: https://github.com/practicalli/spacemacs/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with anchor
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized: # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS_GENERATE, true]

  # Redirect pages when moved or changed
  # - redirects:
  #     redirect_maps:
  #       changelog/insiders.md: insiders/changelog.md
  #       reference/meta-tags.md: reference/index.md

# Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-YBK519HFM6
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - index.md
      - REPL Workflow: introduction/repl-workflow.md
      - Why Spacemacs:
          - introduction/why-spacemacs/index.md
          - Extensive Languages: introduction/why-spacemacs/extensive-language-support.md
          - Mneomic Menus: introduction/why-spacemacs/mnemonic-menu.md
          - Multi-modal Editing: introduction/why-spacemacs/states.md
          - Layer Configuration: introduction/why-spacemacs/layers.md
          - Clojure Support: introduction/why-spacemacs/clojure-layer.md
          - Structural Editing: introduction/why-spacemacs/structural-editing.md
          - Selection Narrowing: introduction/why-spacemacs/helm.md
            # - introduction/why-spacemacs/helm-transient-state.md  # TODO: move content to helm.md
          - introduction/why-spacemacs/project-file-navigation.md
          - introduction/why-spacemacs/layouts.md
          # - introduction/why-spacemacs/configuring-spacemacs.md
      - Mini-cheatsheet: spacemacs-mini-cheatsheet.md
      - Contributing: introduction/contributing.md
      - Writing Tips: introduction/writing-tips.md
      - Resources: introduction/additional-resources.md
  - Pre-install: install-spacemacs/pre-install.md
  - Install:
      - install-spacemacs/index.md
      - Manual Configuration: install-spacemacs/manual-configuration.md
      - Clojure Layer: install-spacemacs/clojure-layer.md
      - Enhance Clojure:
          - install-spacemacs/enhance-clojure-experience.md
          - Smartparens: install-spacemacs/smartparens.md
          - Evil Structural Editing: install-spacemacs/evil-structural-editing.md
          - install-spacemacs/clj-kondo-via-lsp.md
      - Clojure LSP:
          - install-spacemacs/clojure-lsp/index.md
          - install-spacemacs/clojure-lsp/configure-lsp-and-cider.md
          - install-spacemacs/clojure-lsp/snippets.md
      - Font: install-spacemacs/change-font.md
      - Full Screen: install-spacemacs/maximised-full-screen.md
      - Themes: install-spacemacs/themes.md
      - Line Numbers: install-spacemacs/line-numbers.md
      - Emacs Shell: install-spacemacs/eshell.md
      - Start Emacs Instantly:
          - install-spacemacs/emacsclient-server.md
          - Git Commit Message: install-spacemacs/emacsclient-git-commit-messages.md
      - Update Spacemacs:
          - install-spacemacs/update.md
          - Switch to develop: install-spacemacs/switch-to-develop.md
      - Troubleshoot: install-spacemacs/troubleshooting.md
  - Spacemacs Basics:
      - spacemacs-basics/index.md
      - spacemacs-basics/emacs-basics.md
      - Projects:
          - spacemacs-basics/working-with-projects/index.md
          - spacemacs-basics/working-with-projects/dird.md
          - spacemacs-basics/working-with-projects/layouts.md
          - spacemacs-basics/working-with-projects/managing-buffers.md
          - spacemacs-basics/working-with-projects/managing-windows.md
          - spacemacs-basics/working-with-projects/open-and-create-files.md
          - spacemacs-basics/working-with-projects/projectile.md
          - spacemacs-basics/working-with-projects/ranger.md
          - spacemacs-basics/working-with-projects/searching-projects.md
          - spacemacs-basics/working-with-projects/tidying-up-buffers.md
          - spacemacs-basics/working-with-projects/treemacs.md
      - spacemacs-basics/visual-select.md
      - spacemacs-basics/spell-checking.md
  - Evil Basics:
      - spacemacs-basics/evil/index.md
      - spacemacs-basics/evil/editing-states.md
      - spacemacs-basics/vim-style/key-binding-reference.md
      - spacemacs-basics/vim-style/speaking-evil.md
      - spacemacs-basics/vim-style/vim-quick-reference.md
      - spacemacs-basics/vim-style/vim-tips-for-developers.md
      - spacemacs-basics/evil-g-menu.md
      - spacemacs-basics/evil-z-menu.md
      - Evil Tools:
          - spacemacs-basics/evil-tools/index.md
          - spacemacs-basics/evil-tools/helm-swoop.md
          - spacemacs-basics/evil-tools/iedit.md
          - spacemacs-basics/evil-tools/iedit-in-action.md
          - spacemacs-basics/evil-tools/narrowing.md
          - spacemacs-basics/evil-tools/replacing-text-across-projects.md
          - spacemacs-basics/evil-tools/multiple-cursors.md
  - Clojure:
      - clojure-development/index.md
      - REPL:
          - clojure-repl/index.md
          - clojure-repl/connect-to-repl.md
          - clojure-repl/connect-to-remote-repl.md
          - clojure-repl/jack-in-to-repl.md
          - clojure-repl/portal-data-visualization.md
          - clojure-repl/clojurescript-repl.md
          - clojure-repl/refresh-restart-repl.md
          - clojure-repl/component-lifecycle.md
          - clojure-repl/clear-repl-buffer.md
      - Project Config:
          - clojure-development/project-configuration/index.md
          - Monorepo: clojure-development/project-configuration/monorepo-nested-projects.md
      - Documentation:
          - documentation/index.md
          - Comments: documentation/comments.md
          - Apropos: documentation/apropos.md
          - Cider-doc: documentation/cider-doc.md
          - Javadoc: documentation/javadoc.md
      - Evaluate Clojure:
          - evaluating-clojure/index.md
          - Expressions: evaluating-clojure/expressions.md
          - Inspect Values: evaluating-clojure/inspect.md
          - Interrupt Eval: evaluating-clojure/interrupt.md
          - Remove Eval: evaluating-clojure/undefine.md
          - Intermediate values: evaluating-clojure/enlighten.md
          - Macro Expand: evaluating-clojure/macro-expand.md
          - evaluating-clojure/evaluate-in-repl-buffer.md
      - Testing:
          - testing/index.md
          - testing/kaocha-test-runner.md
          - testing/unit-testing/index.md
          - testing/unit-testing/cider-test-deps-edn-projects.md
          - testing/unit-testing/writing-unit-tests.md
          - testing/unit-testing/running-tests.md
          - testing/unit-testing/re-run-tests-from-test-report-buffer.md
          - testing/unit-testing/refactor-unit-tests.md
          - testing/unit-testing/configure-cider-test-runner.md
      - Navigating Code:
          - navigating-code/index.md
          - Expressions: navigating-code/expressions.md
          - Markers: navigating-code/markers.md
          - Namespaces: navigating-code/namespaces.md
          - Symbols: navigating-code/names-symbols.md
          - Functions: navigating-code/function-definitions.md
          - Java: navigating-code/java-definitions.md
          - Code Folding: navigating-code/code-folding.md
          - Find Uses: navigating-code/find-usages.md
      - Structural Editing:
          - structural-editing/index.md
          - Smartparens: structural-editing/smartparens.md
          - Evil Cleverparens: structural-editing/cleverparens.md
          - Lisp State:
              - structural-editing/lisp-state/index.md
              - Wrap Unrap: structural-editing/lisp-state/wrap-unwrap.md
              - Slurp Barf: structural-editing/lisp-state/slurp-barf.md
              - Deleting: structural-editing/lisp-state/deleting.md
              - Raising: structural-editing/lisp-state/raising.md
      - Snippets:
          - snippets/index.md
          - Clojure LSP:
              - snippets/clojure-lsp/index.md
              - snippets/clojure-lsp/custom-snippets.md
              - snippets/clojure-lsp/practicalli-snippets.md
          - Yasnippets:
              - snippets/yasnippets/index.md
              - snippets/yasnippets/built-in-snippets.md
              - snippets/yasnippets/clojure-snippets-reference.md
              - snippets/yasnippets/create-snippets.md
              - snippets/yasnippets/practicalli-snippets.md
              - snippets/yasnippets/writing-snippets.md
      - Refactor:
          - refactor/index.md
          - Function: refactor/functions.md
          - Namespace: refactor/namespace.md
          - Project: refactor/project.md
          - Clojure Mode: refactor/clojure-mode.md
          - Clojure LSP: refactor/clojure-lsp.md
      - Debug:
          - debug-clojure/index.md
          - Understand Errors: debug-clojure/understanding-errors.md
          - Format Errors: debug-clojure/format-error-messages.md
          - Inspect values: debug-clojure/inspect-values.md
          - Cider debug: debug-clojure/cider-debug.md
          - Classpath Issues: debug-clojure/classpath-issues.md
          - core-async: debug-clojure/core-async.md
          - Sayid Debug: debug-clojure/sayid-debug.md
      - Code Quality:
          - improving-code/index.md
          - improving-code/live-linting.md
          - improving-code/batch-linting.md
          - improving-code/idiomatic-code-checking.md
          - improving-code/formatting.md
  - Source Control:
      - source-control/index.md
      - Git Layer: source-control/configure-layers.md
      - Git Config: source-control/git-configuration.md
      - Forge Config: source-control/forge-configuration.md
      - GitHub Clone: source-control/github-clone.md
      - Magit Git Client:
          - source-control/magit/index.md
          - source-control/magit/create-local-repository.md
          - source-control/magit/list-local-repositories.md
          - source-control/magit/status.md
          - source-control/magit/branching.md
          - source-control/magit/staging-changes.md
          - source-control/magit/stashing.md
          - source-control/magit/commit-changes.md
          - source-control/magit/tag-commit.md
          - source-control/magit/timemachine.md
          - source-control/magit/reset-commit-history.md
          - source-control/magit/interactive-rebasing.md
          - source-control/magit/cherry-picking.md
          - source-control/magit/blame.md
          - source-control/magit/clean-up-magit-sessions.md
          - source-control/magit/version-highlighting.md
          - Remote Repository:
              - source-control/magit/remote-repositories/index.md
              - source-control/magit/remote-repositories/add-remote.md
              - source-control/magit/remote-repositories/checkout-remote-branch.md
              - source-control/magit/remote-repositories/clone.md
              - source-control/magit/remote-repositories/configure-default-push.md
              - source-control/magit/remote-repositories/configure-default-upstream.md
              - source-control/magit/remote-repositories/pull-changes.md
              - source-control/magit/remote-repositories/push-changes.md
              - source-control/magit/remote-repositories/try-pull-requests.md
          - Magit Forge:
              - source-control/magit/forge/index.md
              - Add Repository to Database: source-control/magit/forge/add-repository-to-database.md
              - Remote Fork: source-control/magit/forge/forks.md
              - Manage Issues: source-control/magit/forge/issues.md
              - Manage Pull Requests: source-control/magit/forge/pull-requests.md
  - Markdown:
      - markdown-mode/index.md
  - Org-mode:
      - org-mode/index.md
      - org-mode/headings.md
      - org-mode/lists-and-checkboxes.md
      - org-mode/linking.md
      - org-mode/todo-states.md
      - org-mode/tables.md
      - org-mode/code-blocks.md
      - org-mode/org-mode-tweaks.md
      - org-mode/org-journal.md
      - org-mode/yasnippets.md
      - org-mode/literate-programming/index.md
  - Database:
      - database-access/index.md
      - database-access/add-sql-layer-and-lsp.md
      - database-access/connection-configuration.md
      - database-access/external-dependencies.md
      - database-access/using-sql.md
  - Ultra-Mobile Neovim:
      - termux/index.md
      - F-Droid: termux/fdroid-install.md
      - Termux Setup: termux/setup.md
      - Using Termux: termux/using-termux.md
      - Git: termux/git.md
      - Zsh: termux/custom-shell.md
      - Clojure: termux/clojure-development.md
      - Spacemacs: termux/spacemacs.md
  - Misc:
      - misc/index.md
      - misc/artist-mode.md
      - misc/unicode-characters.md
  - Reference:
      - reference/index.md
      - reference/emacs-quick-reference.md
      - reference/spacemacs-conventions.md
      - reference/hydra-menus.md
      - reference/projectile.md
      - reference/cider/index.md
      - reference/cider/configuration-variables.md
      - Clojure REPL:
          - external-repl/index.md
          - external-repl/connect-to-running-repl.md
          - external-repl/switching-to-repl.md
          - external-repl/show-repl-on-connect.md
          - external-repl/repl-command-menu.md
          - external-repl/repl-history.md
      - Clojure Standard Library:
          - reference/clojure/index.md
          - reference/clojure/control-flow.md
          - reference/clojure/data-structures.md
          - reference/clojure/functions.md
          - reference/clojure/maths.md
          - reference/clojure/strings.md
      - Clojure LSP:
          - reference/clojure-lsp/index.md
          - LSP Variables: reference/clojure-lsp/lsp-variables-reference.md
      - reference/structural-editing/smartparens-cheatsheet.md
      - reference/keybindings/index.md
      - reference/keybindings/cider-keybindings.md
      - reference/keybindings/vim-keybindings.md
      - reference/vim/getting-comfortable.md
      - reference/vim/key-bindings.md
      - os-specific-config/macosx.md
  - Emacs:
      - emacs-lisp/index.md
      - encryption/index.md
      - encryption/create-gpg-key.md
      - writing-emacs-lisp/index.md
  - Alternative Tools:
      - alternative-tooling/index.md
      - alternative-tooling/leiningen.md
      - alternative-tooling/org-easy-templates.md
  - To Review:
      - spacemacs-basics/vim-style/common-evil.md
      - introduction/why-spacemacs/why-evil.md
